# Copyright 2025 Vinicius Fortuna
# SPDX-License-Identifier: 	Apache-2.0

# This demo toggles the RGB LED when the boot button is pressed.
# The RGB LED randomly rotates colors.

packages:
  board: !include ./board.yaml

esphome:
  name: board-demo
  friendly_name: Board Demo

logger:

binary_sensor:
  - id: !extend boot_button
    on_release:
      - if:
          condition:
            light.is_on: rgb
          then:
            - light.turn_off:
                id: rgb
                transition_length: 0.5s
          else:
            - light.turn_on:
                id: rgb
                brightness: 0.3
                effect: random

light:
  - id: !extend rgb
    effects:
      - random:
          transition_length: 1s
          update_interval: 1s
