# Copyright 2025 Vinicius Fortuna
# SPDX-License-Identifier: 	Apache-2.0

packages:
  board: !include ./board.yaml

esphome:
  name: board-demo
  friendly_name: Board Demo
  on_boot:
    priority: -100
    then:
      - logger.log: "Board Demo started"
      - micro_wake_word.enable_model: okay_nabu
      - micro_wake_word.enable_model: stop
      - micro_wake_word.start:

logger:

wifi:
  ap:

captive_portal:

web_server:
  version: 3

lvgl:
  displays: [box_display]

micro_wake_word:
  microphone:
    microphone: box_microphone
    channels: 0
    gain_factor: 4
  vad:
  models:
    - model: https://github.com/kahrendt/microWakeWord/releases/download/okay_nabu_20241226.3/okay_nabu.json
      id: okay_nabu
    - model: https://github.com/kahrendt/microWakeWord/releases/download/stop/stop.json
      id: stop
      internal: true
  stop_after_detection: false
  on_wake_word_detected:
    then:
      - logger.log:
          format: "Wake word detected: %s"
          args: ['wake_word.c_str()']
      - if:
          condition:
            lambda: 'return wake_word == "Okay Nabu";'
          then:
            - media_player.speaker.play_on_device_media_file:
                id: main_media_player
                media_file: wake_word_triggered_sound
                announcement: true

media_player:
  - id: main_media_player
    name: Media Player
    platform: speaker
    volume_min: 0.1
    volume_max: 0.8
    announcement_pipeline:
      speaker: box_speaker
      format: FLAC
      num_channels: 1  # Stereo is unnecessary for announcements.

    files:
      # From https://github.com/esphome/home-assistant-voice-pe/blob/dev/home-assistant-voice.yaml
      - id: mute_switch_on_sound
        file: https://github.com/esphome/home-assistant-voice-pe/raw/dev/sounds/mute_switch_on.flac
      - id: mute_switch_off_sound
        file: https://github.com/esphome/home-assistant-voice-pe/raw/dev/sounds/mute_switch_off.flac
      - id: wake_word_triggered_sound
        file: https://github.com/esphome/home-assistant-voice-pe/raw/dev/sounds/wake_word_triggered.flac

    on_announcement:
      - logger.log: Media player announcing
      # The microphone needs to release the i2s before we can use it for playback.
      - micro_wake_word.stop:
      - wait_until:
          speaker.is_playing: box_speaker
      - logger.log: Speaker is playing
    on_play:
      - logger.log: Media player playing
    on_pause:
      - logger.log: Media player paused
    on_idle:
      - logger.log: Media player is idle
      - wait_until:
          speaker.is_stopped: box_speaker
      - logger.log: Speaker stopped
      # Resume wake word dection once the i2s is released.
      # TODO: Figure out how to use i2s full duplex mode to avoid this.
      - micro_wake_word.start:
      - wait_until:
          microphone.is_capturing: box_microphone
      - logger.log: Microphone is capturing

binary_sensor:
  - id: !extend mute_status
    on_press:
      - micro_wake_word.stop:
      - media_player.speaker.play_on_device_media_file:
          id: main_media_player
          media_file: mute_switch_on_sound
          announcement: true
    on_release:
      - media_player.speaker.play_on_device_media_file:
          id: main_media_player
          media_file: mute_switch_off_sound
          announcement: true
