# Copyright 2025 Vinicius Fortuna
# SPDX-License-Identifier:  Apache-2.0

# This demo exercises the microphone as an Analog Sound Level Meter.
# It continuously measures the ambient noise level and sets the light
# brightness to match the sound level.

packages:
  board: !include ./board.yaml

esphome:
  name: sound-level-meter
  friendly_name: Sound Level Meter

logger:

sensor:
  - platform: sound_level
    microphone: echo_microphone
    id: sound_level_sensor
    passive: false
    measurement_duration: 50ms
    rms:
      name: "Sound Level"
      unit_of_measurement: "%"
      accuracy_decimals: 1
      filters:
        - multiply: 100
      on_value:
        then:
          - light.turn_on:
              id: echo_led
              # The sensor value is from 0.0 to 1.0.
              brightness: !lambda "return x / 100.0;"
