# Copyright 2025 Vinicius Fortuna
# SPDX-License-Identifier:  Apache-2.0

# This demo exercises the microphone as an Analog Sound Level Meter.
# It continuously measures the ambient noise level and sets the light
# brightness to match the sound level.

packages:
  board: !include ./board.yaml

esphome:
  name: sound-level-meter
  friendly_name: Sound Level Meter

logger:

sensor:
  - platform: sound_level
    microphone: echo_microphone
    id: sound_level_sensor
    passive: false
    measurement_duration: 50ms
    rms:
      name: "Sound Level"
      on_value:
        then:
          - light.turn_on:
              id: echo_led
              brightness: !lambda |-
                // The sound level is in dB, from approx -80 (quiet) to 0 (loud).
                // Map it to a brightness from 0.0 to 1.0.
                // We'll use a range of -60 to 0 dB.
                const float db_min = -60.0;
                const float db_max = 0.0;
                float brightness = (x - db_min) / (db_max - db_min);
                // Clamp to the valid range
                if (brightness < 0.0) brightness = 0.0;
                if (brightness > 1.0) brightness = 1.0;
                return brightness;
