# Copyright 2025 Vinicius Fortuna
# SPDX-License-Identifier: 	Apache-2.0

esphome:

esp32:
  board: esp32dev
  # board: esp32doit-devkit-v1
  framework:
    type: esp-idf

binary_sensor:
  - id: boot_button
    platform: gpio
    name: Boot Button
    pin:
      number: GPIO00
      inverted: true

output:
  - id: led_output
    platform: ledc
    pin: GPIO02

light:
  - id: led
    platform: monochromatic
    name: Board LED
    output: led_output
