# Copyright 2025 Vinicius Fortuna
# SPDX-License-Identifier: 	Apache-2.0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

binary_sensor:
  - id: boot_button
    platform: gpio
    name: Boot Button
    pin:
      number: GPIO09
      inverted: true
      mode:
        input: true
        pullup: true

light:
  - id: rgb
    name: Board RGB Light
    platform: esp32_rmt_led_strip
    pin: GPIO10
    chipset: WS2812
    num_leds: 1
    rgb_order: rgb
