# Copyright 2025 Vinicius Fortuna
# SPDX-License-Identifier: 	Apache-2.0

# This demo randomly rotates the colors on the RGB LED, and
# toggles the blue LED when the boot button is pressed.

packages:
  board: !include ./board.yaml

esphome:
  name: board-demo
  friendly_name: Board Demo
  on_boot: 
    then:
      - light.turn_on:
          id: rgb
          brightness: 0.2
          effect: random

logger:

binary_sensor:
  - id: !extend boot_button
    on_release:
      - light.toggle:
          id: led
          transition_length: 0.5s

light:
  - id: !extend rgb
    effects:
      - random:
          transition_length: 1s
          update_interval: 1s
